//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_product
    {
        public int order_id { get; set; }
        public Nullable<int> pet_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public int quantity { get; set; }
    
        public virtual item item { get; set; }
        public virtual order order { get; set; }
        public virtual pet pet { get; set; }
    }
}
